accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('signup/',views.signup, name="signup"),
    path('login/',views.login, name='login'),
    path('logout/',views.logout,name="logout"),
    path('delete/',views.delete, name= "delete"),
    path('update/',views.update, name="update"),
    path('password/',views.password,name="password"),
    ]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('',views.index,name="index"),
    path('new/',views.create,name="create"),
    path('<int:board_pk>/',views.detail,name="detail"),
    path('<int:board_pk>/delete/',views.delete,name="delete"),
    path('<int:board_pk>/edit/',views.update,name="update"),
    ]

django_fbv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/',include('boards.urls')),
    path('accounts/',include('accounts.urls')),
    path('users/',include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('',views.index,name="index"),
    path('<int:user_pk>/',views.detail, name = "detail"),
    ]

boards/models.py
from django.db import models
from django.urls import reverse
# from django.contrib.auth.models import User # 사용하지 마세요.
# from django.contrib.auth import get_user_model 
from django.conf import settings
# settings.AUTH_USER_MODEL 
# default 값이 'auth.User'

# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    hit = models.IntegerField(default=0, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    
    def __str__(self):
        return f'<Board ({self.id})> : {self.title}'
        
    
    def get_absolute_url(self):
        # f'/self.pk/'
        return reverse('boards:detail',args=[self.pk])

boards/forms.py
from django import forms
from .models import Board
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

# class BoardForm(forms.Form):
#     title = forms.CharField(label="제목", max_length=10,
#                             error_messages={"required":"제목써라"}
#                             )
                            
                            
#     content = forms.CharField(label="내용", 
#                             error_messages={"required":"내용써라"},
#                             widget=forms.Textarea(attrs={
#                                 'placeholder':"내용쓰자",
#                                 'class':'input-box'
#                             })
#                             )
                            
# modelform
# 중복제거를 위한. 모델이 있는경우 이런경우는 편하게...
class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        # fields = '__all__'
        fields = ('title','content')
        # widgets = {'title': forms.TextInput(attrs={
        #                                     'placeholder':'제목써라',
        #                                     'class':'title'
        #                                     }),
        #             'content':forms.Textarea(attrs={
        #                                     'placeholder':'내용써라',
        #                                     'class':'content'
        #                                     })
        #             }
    
        # error_messages = {'title':{
        #                         'required':'제목은 반드시 써라'
        #                         },
        #                     'content': {
        #                             'required':'내용은 반드시 써라'
        #                     }
        #                 }


        # #크리스피 한정                
        # def __init__(self, *args, **kwargs):
        #     super().__init__(*args, **kwargs)
        #     self.helper = FormHelper()
        #     self.helper.form_method = "POST"
        #     self.helper.add_input(Submit('submit','제출~!'))

boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
import hashlib
from .models import Board
from .forms import BoardForm

# Create your views here.
# @login_required
def index(request):
    boards = Board.objects.order_by('-pk')
    if request.user.is_authenticated:
        gravatar_url = hashlib.md5(request.user.email.strip().lower().encode('utf-8')).hexdigest()
    else:
        gravatar_url = None
        # d0e53a9a9bbc9cf481144a929930f41c
    context = {
        'boards':boards,
        'gravatar_url':gravatar_url,
        }
    return render(request, 'boards/index.html',context)

@login_required
def create(request):
    # if not request.user.is_authenticated:
    #     return redirect('boards:index')
    
    if request.method == "POST":
        board_form = BoardForm(request.POST)
        # title = request.POST.get('title')
        # content = request.POST.get('content')
        if board_form.is_valid(): #유효하면
            # title = board_form.cleaned_data.get('title') #정제된 데이터를 가져온다.
            # content = board_form.cleaned_data.get('content')
            # board = Board(title=title,content=content)
            # board.save()
            board = board_form.save(commit=False) #위의 주석4줄과 동일함.
            board.user = request.user
            board.save()
            return redirect(board)
    else:
        board_form = BoardForm()
        
    context = {
        'board_form':board_form
        }
    return render(request,'boards/form.html',context)
    
def detail(request,board_pk):
    # board = Board.objects.get(pk=board_pk) #사용자가 없는 값을 입력하면 에러가 떠, 그래서 get_object_or_404를 import 해줘
    board = get_object_or_404(Board,pk=board_pk)
    board.hit += 1
    board.save()
    context = {
        "board":board
    }
    return render(request,'boards/detail.html',context)
    
def delete(request,board_pk):
    board = get_object_or_404(Board,pk=board_pk)
    if request.user == board.user:
        if request.method == "POST":
            board.delete()
            return redirect('boards:index')
        else:
            return redirect(board)
    else:
        return redirect(board)
        
        
def update(request, board_pk):
    # 1. board_pk에 해당하는 오브젝트를 가져온다.
    #    - 없으면, 404
    #    - 있으면, board = Board.objects.get(pk=board_pk) 와 동일
    board = get_object_or_404(Board, pk=board_pk)
    if request.user == board.user:
        # 2-1. POST 요청이면 (사용자가 form을 통해 데이터를 보내 준 것.)
        if request.method == "POST":
            # 사용자 입력값(request.POST)을 BoardForm에 전달해주고, 
            board_form = BoardForm(request.POST, instance=board)
            # 검증 (유효성 체크)
            if board_form.is_valid():
                # board.title = board_form.cleaned_data.get('title')
                # board.content = board_form.cleaned_data.get('content')
                # board.save()
                board = board_form.save() # 위 주석 3줄과 동일
                return redirect(board)
        # 2-2. GET 요청이면 (수정하기 버튼을 눌렀을 때)
        else:
            # BoardForm을 초기화 (사용자 입력값을 넣어준 상태)
            # board_form = BoardForm(initial=board.__dict__)
            board_form = BoardForm(instance=board)
        # context에 담겨있는 board_form은 두 가지 상황이 있다.
        # 1 - POST 요청에서 검증에 실패하였을 때, 오류 메세지가 포함된 상태
        # 2 - GET 요청에서 초기화된 상태
        context = {
            'board_form': board_form
        }    
        return render(request,'boards/form.html',context)
    else:
        return redirect(board)
    
    

boards/templates/boards/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>FBV</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    {% if messages %}
    {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{ message.tags }}" role="alert"{% endif %}> {{ message }} </div>
    {% endfor %}
        <!--</ul>-->
    {% endif %}
    
    
    
    
    {% if user.is_authenticated %}
        {% load gravatar %}
        <img src="https://s.gravatar.com/avatar/{{ user.email|makehash }}?s=150&d=https://stickershop.line-scdn.net/stickershop/v1/product/8542/LINEStorePC/main.png;compress=true">
        <h1>{{ user }}님 환영합니다 :)</h1>
        <a href="{% url 'accounts:logout' %}">로그아웃</a>
        <a href="{% url 'accounts:update' %}">프로필수정</a>
        <form action="{% url 'accounts:delete' %}" method="POST" onsubmit="return confirm('탈퇴할거야?')">
            {% csrf_token %}
            <input type="submit" value="회원탈퇴">
        </form>
    {% else %}
        <a href="{% url 'accounts:signup' %}">회원가입</a>
        <a href="{% url 'accounts:login' %}">로그인</a>
    {% endif %}
    {% block body %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

boards/templates/boards/create.html
{% extends 'boards/base.html' %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    <!--<input type="text" name="title"><br>-->
    <!--<textarea name="content"></textarea>-->
    
    <!--p태그로 감싸준다-->
    {{ board_form.as_p }} 
    <input type="submit">
</form>


{% endblock %}

boards/templates/boards/detail.html
{% extends 'boards/base.html' %}

{% block body %}
<h1>{{ board.pk }} 번째 글</h1>
<h2>{{ board.title }}</h2>
<h3>작성자 : {{ board.user }}</h3>
<p>조회수 : {{ board.hit }}</p>
<hr>
<p> {{ board.content }}</p>
{% if request.user == board.user %}
<form action="{% url 'boards:delete' board.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제">
</form>
<br>
<a href="{% url 'boards:update' board.pk %}">수정하기</a>
{% endif %}
{% endblock %}

boards/templates/boards/form.html
{% extends 'boards/base.html' %}

{% block body %}
{% load crispy_forms_tags %}
{% if request.resolver_match.url_name == 'create' %}
    <br>
    <h1>글 생성</h1>
{% else %}
    <h1>글 수정</h1>
{% endif %}
<form method="POST">
    {% csrf_token %}
    <!--<input type="text" name="title"><br>-->
    <!--<textarea name="content"></textarea>-->
    
    <!--{% for field in board_form %}-->
    <!--    {{ field.errors }}-->
    <!--    {{ field.label_tag }} {{ field }}-->
    <!--{% endfor %}-->
    <!--p태그로 감싸준다-->
    {{ board_form|crispy }} 
    <input type="submit">
</form>

<form method="POST">
    {{ board_form.title }}
    {{ board_form.content }}
</form>

{% endblock %}

boards/templates/boards/index.html
{% extends 'boards/base.html' %}

{% block body %}
<h1>게시글 목록</h1>
{% if user.is_authenticated %}
    <a href="{% url 'boards:create' %}"
{% endif %}

<a href="{% url 'boards:create' %}">글 쓰러 가기</a>
{% for board in boards %}
    <p>{{board.pk}}</p>
    <p>{{board.title}}</p>
    <a href="{% url 'boards:detail' board.pk %}">글보러가기</a>
    <hr>
{% endfor %}
{% endblock %}