django_fbv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/',include('boards.urls')),
    path('accounts/',include('accounts.urls')),
    path('users/',include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('',views.index,name="index"),
    path('<int:user_pk>/',views.detail, name = "detail"),
    ]

boards/models.py
from django.db import models
from django.urls import reverse
# from django.contrib.auth.models import User # 사용하지 마세요.
# from django.contrib.auth import get_user_model 
from django.conf import settings
# settings.AUTH_USER_MODEL 
# default 값이 'auth.User'

# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    hit = models.IntegerField(default=0, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    
    def __str__(self):
        return f'<Board ({self.id})> : {self.title}'
        
    
    def get_absolute_url(self):
        # f'/self.pk/'
        return reverse('boards:detail',args=[self.pk])

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
# Create your views here.

def index(request):
    User = get_user_model()
    users = User.objects.all()
    context = {'users':users}
    return render(request, 'users/index.html', context)
    
def detail(request, user_pk):
    User = get_user_model()
    user = User.objects.get(pk=user_pk)
    # user_boards = user.board_set.all()
    context = {'user_detail':user}
    # context = {'user_detail':user, 'user_boards':user_boards}
    return render(request, 'users/detail.html',context)

users/templates/users/detail.html
{% extends 'boards/base.html' %}

{% block body %}
    <h1>프로필</h1>
    <p>{{ user_detail.pk }}</p>
    <p>{{ user_detail.username }}</p>
    <p>{{ user_detail.email }}</p>
    {% for board in user_detail.board_set.all %}
        <p> {{ board.title }}</p>
    {% endfor %}
{% endblock %}

users/templates/users/index.html
{% extends 'boards/base.html' %}

{% block body %}
<h1>회원명부</h1>
{% for user in users %}
    <a href = "{% url 'users:detail' user.pk %}">{{ user }}</a>
{% endfor %}
    <p>{{ user }}</p>

{% endblock %}